name: tgfess
description: Telegram Mention Confess (@tgfess)
version: 0.1.0+3
environment:
  sdk: ^2.8.1
dependencies:
  flutter:
    sdk: flutter
  get: ^3.4.3
  dio: ^3.0.10
flutter:
  uses-material-design: true
